language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true

  # There are known failures due to a bug in PHP
  allow_failures:
    php:
      - 5.6
      - 7.0
      - 7.1
      - 7.2
      - nightly

install:
  - composer install --no-interaction
