sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--dev --no-suggest --no-interaction"

matrix:
  include:
    - php: 7.1
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.2
      env:
        - RUN_PHPSTAN=true
        - TEST_COVERAGE=true
        - DEPS=latest
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.3
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - travis_retry composer self-update

install:
  - if [ $DEPS == 'latest' ]; then travis_retry composer update --prefer-source $COMPOSER_ARGS; fi
  - if [ $DEPS == 'lowest' ]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS; fi
  - if [ $TRAVIS_PHP_VERSION == nightly ]; then travis_retry composer update $COMPOSER_ARGS --ignore-platform-reqs; fi

script:
  - if [ "$RUN_PHPSTAN" == "true" ]; then composer phpstan; fi
  - if [[ $TRAVIS_PHP_VERSION != nightly ]]; then composer phpunit; fi
  - if [[ $TRAVIS_PHP_VERSION == nightly ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-text; fi

after_script:
  - if [[ "$TEST_COVERAGE" == "true" ]]; then travis_retry php vendor/bin/php-coveralls; fi