language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer require php-coveralls/php-coveralls:^2.1
  - composer install --no-interaction

before_script:
  - mkdir -p build/logs

script:
  - $phpunit_flags="--verbose --coverage-clover build/logs/clover.xml"
  - if [[ $TRAVIS_PHP_VERSION != nightly ]]; then ./vendor/bin/phpunit $phpunit_flags; fi
  - if [[ $TRAVIS_PHP_VERSION == nightly ]]; then phpdbg -qrr ./vendor/bin/phpunit $phpunit_flags; fi

after_success:
  - travis_retry php vendor/bin/php-coveralls
