name: Test URL
on:
  push:
    paths-ignore:
      - '**.md'

  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: PHP ${{ matrix.php }} ${{ matrix.enable-jit == 1 && 'with' || 'without' }} JIT on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    container: shivammathur/node:latest-${{ matrix.arch }}
    continue-on-error: ${{ matrix.php == 'nightly' }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        arch:
          - amd64
          - i386
        php:
          - 8.0
          - 8.1
        enable-jit:
          - 0
          - 1
        include:
          - php: nightly
            os: ubuntu-latest
            arch: amd64
            enable-jit: 0

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, mbstring, opcache, pcre, gmp
          ini-values: zend.assertions=1, opcache.enable_cli=${{ matrix.enable-jit }}, opcache.memory_consumption=256, opcache.jit=1255, opcache.jit_buffer_size=256M
          coverage: none
        env:
          fail-fast: true

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          if [[ ${{ matrix.php == 'nightly' }} ]]; then
            composer update --no-interaction --ignore-platform-reqs
          else
            composer update --no-interaction
          fi

      - name: Run PHPCS
        run: vendor/bin/phpcs

      - name: Run PHPStan
        run: vendor/bin/phpstan

      - name: Run Tests
        run: vendor/bin/phpunit
